apiVersion: apps/v1
kind: Deployment
metadata:
  name: SubscriptionManagement
  labels:
    app: SubscriptionManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SubscriptionManagement
  template:
    metadata:
      labels:
        app: SubscriptionManagement
    spec:
      containers:
        - name: SubscriptionManagement
          image: "username/SubscriptionManagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
