apiVersion: v1
kind: Service
metadata:
  name: SubscriptionManagement
  labels:
    app: SubscriptionManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: SubscriptionManagement