apiVersion: v1
kind: Service
metadata:
  name: ManuscriptPublication
  labels:
    app: ManuscriptPublication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ManuscriptPublication