---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: AuthorManagement
  labels:
    app: AuthorManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthorManagement
  template:
    metadata:
      labels:
        app: AuthorManagement
    spec:
      containers:
        - name: AuthorManagement
          image: username/AuthorManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: SubscriptionManagement
  labels:
    app: SubscriptionManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SubscriptionManagement
  template:
    metadata:
      labels:
        app: SubscriptionManagement
    spec:
      containers:
        - name: SubscriptionManagement
          image: username/SubscriptionManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarymanagement
  labels:
    app: librarymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librarymanagement
  template:
    metadata:
      labels:
        app: librarymanagement
    spec:
      containers:
        - name: librarymanagement
          image: username/librarymanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pointmanagement
  labels:
    app: pointmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pointmanagement
  template:
    metadata:
      labels:
        app: pointmanagement
    spec:
      containers:
        - name: pointmanagement
          image: username/pointmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ManuscriptPublication
  labels:
    app: ManuscriptPublication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ManuscriptPublication
  template:
    metadata:
      labels:
        app: ManuscriptPublication
    spec:
      containers:
        - name: ManuscriptPublication
          image: username/ManuscriptPublication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: AuthorManagement
  labels:
    app: AuthorManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: AuthorManagement


---


apiVersion: v1
kind: Service
metadata:
  name: SubscriptionManagement
  labels:
    app: SubscriptionManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: SubscriptionManagement


---


apiVersion: v1
kind: Service
metadata:
  name: librarymanagement
  labels:
    app: librarymanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: librarymanagement


---


apiVersion: v1
kind: Service
metadata:
  name: pointmanagement
  labels:
    app: pointmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: pointmanagement


---


apiVersion: v1
kind: Service
metadata:
  name: ManuscriptPublication
  labels:
    app: ManuscriptPublication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ManuscriptPublication

